name: BattleRoyale
main: io.github.gmills82.battleroyale.BattleRoyalePlugin
version: 1.004.000
commands:
  beginBattleRoyale:
    description: Begin the Battle Royale
    usage: /<command> [battlename] [players]
    permission: <plugin name>.basic
    permission-message: You don't have <permission>
  pauseBattleRoyale:
    description: Pause the Battle Royale
    usage: /<command>
    permission: <plugin name>.basic
    permission-message: You don't have <permission>
  resumeBattleRoyale:
    description: Resume the Battle Royale
    usage: /<command>
    permission: <plugin name>.basic
    permission-message: You don't have <permission>
  floodBR:
      description: Begin flood catastrophy
      usage: /<command>
      permission: <plugin name>.basic
      permission-message: You don't have <permission>